apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets
  namespace: drivecloud

type: Opaque

stringData:
  PORT: "5001"

  MONGODB_URI: "mongodb+srv://kundankumarsingh2005_db_user:VOVbjIm3pO8xaaG6@cluster0.zmij82y.mongodb.net/drivecloud?retryWrites=true&w=majority&appName=Cluster0"

  JWT_SECRET: "supersecretjwt"

  JWT_REFRESH_SECRET: "superrefreshsecret"

  SMTP_USER: "your@email.com"

  SMTP_PASS: "yourpassword"

  NODE_ENV: "production"
